### ISSUE TITLE
Entering the pool without a suit on softlocks you.

### ISSUE THREAD

**Issue by Bokkiewokkie** [GameWyrm/hearths-neighbor-2#2]
While exploring the station without a suit on, I wandered into Aquarius' room and wanted to jump in the water to see if I could dive down. It turns out this just gets you trapped as there's no ledge to walk out of the pool again and bouncing on the water doesn't get you high enough at normal gravity to let you back out.
So the only options you have to get out are to reset, meditate, or wait for the gravity to lower. Some way to just walk out normally would be appreciated.

**Comment by GameWyrm** [comment]
lol

Alright, I can add a ramp to get out

**Comment by GameWyrm** [comment]
Fixed in [1.0.2](https://github.com/GameWyrm/hearths-neighbor-2/releases/tag/v1.0.2).
